DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS volumes CASCADE;
DROP TABLE IF EXISTS networks CASCADE;
DROP TABLE IF EXISTS containers CASCADE;
DROP TABLE IF EXISTS docker_hosts CASCADE;
DROP TABLE IF EXISTS users CASCADE;
