apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: docker-dashboard
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
